[package]
name = "day_1"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fetch_input"
path = "tools/fetch_input.rs"


[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
